format_version: 0.3.0

name: Nucleoli Segmentation
description: todo
authors: todo

cite: todo

git_repo: https://github.com/Ahanio/nucleoli_segment
tags: [unet2d, pytorch, nucleoli, segmentation]
license: MIT

documentation: todo
covers: todo # todo unet 2d arch image
attachments: {}
timestamp: 2021-03-22T12:22:32Z  # ISO 8601

inputs:
  - name: raw
    description: raw input
    axes: bcyx  # letters of axes in btczyx
    data_type: float32
    data_range: [-inf, inf]
    shape: [1, 96, 512, 512]

outputs:
  - name: mask
    description: predict in [0,1]
    axes: bcyx
    data_type: float32
    data_range: [0, 1]
    shape: [1, 1, 512, 512]

language: python
framework: pytorch
source: ./all_in_one.py:AllInOneModel
kwargs: {focus_frame_idx: 41} 
dependencies: conda:./environment_droplet.yml

test_inputs: [./test_input.npy]
test_outputs: [./test_output.npy]

weights: 
  pytorch_script:
    sha256: 80be9abec30c4b7219999516247740c16422ef9f975aea1d760c9d18b87597c0
    source: https://www.dropbox.com/s/c7kb86s55lyidfv/nucleoli_weights.tar?dl=0 #./weights/nucleoli_weights.tar  