format_version: 0.3.0

name: Nucleoli Segmentation
description: todo
authors: todo

# we allow for multiple citations. Each citation contains TEXT, DOI and URL. One of DOI or URL needs to be given.
cite: todo

git_repo: 
tags: [unet2d, pytorch, nucleoli, segmentation]
license: MIT

documentation: todo
covers: []  # todo unet 2d arch image
attachments: {}
timestamp: 2020-01-28T12:22:32Z  # ISO 8601

inputs:
  - name: raw
    description: raw input
    axes: bcyx  # letters of axes in btczyx
    data_type: float32
    data_range: [-inf, inf]
    shape: [1, 7, 512, 512]

outputs:
  - name: mask
    description: probability in [0,1]
    axes: bcyx
    data_type: float32
    data_range: [0, 1]
    halo: [0, 0, 32, 32]
    shape: [1, 1, 512, 512]

language: python
framework: pytorch
source: todo #pybio.torch.models.unet2d.UNet2d
dependencies: conda:../environment.yaml

# test_inputs: [test_input.npy]
# test_outputs: [test_output.npy]

# sample_inputs: [sample_input.npy]
# sample_outputs: [sample_output.npy]

weights: todo
#  pytorch_state_dict:
#    authors: [Constantin Pape;@bioimage-io]
#    sha256: e4d3885bccbe41cbf6c1d825f3cd2b707c7021ead5593156007e407a16b27cf2
#    source: https://zenodo.org/record/3446812/files/unet2d_weights.torch